---
fetch_interval: 1
team_id: 7
telegram:
  api_key: ""
  channel_name: "bvbspielwarnung"
warnings:
  intervals:
    - 24
    - 6
    - 3
    - 1
  home_title: "ğŸ Heimspiel"
  home_message: "Vermeide U42 / U46 / Kreuzviertel / Borsigplatz / Uni-Parkplatz"
  guest_title: "ğŸ•AuswÃ¤rtsspiel"
  guest_message: "Vermeide Kneipen mit TV"

